apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: jenkins
  annotations:
    # This annotation is the Bridge to Google Cloud!
    iam.gke.io/gcp-service-account: jenkins-sa@${PROJECT_ID}.iam.gserviceaccount.com